In [1]:
# Importing Essential Libraries for Data Cleaning
import numpy as np
import pandas as pd

In [2]:
# pd.rea_csv("File location") is used to import Dataset
df = pd.read_csv("job_descriptions.csv")

In [3]:
# .head() shows the first lines of dataset
df.head(5)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

In [4]:
# .tail() shows last lines of dataset
df.tail(5)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
1615935,134563577088850,0 to 12 Years,B.Tech,$64K-$114K,"Malabo (de jure),",Equatorial Guinea,1.6508,10.2679,Full-Time,18281,...,950-451-5843,Mechanical Engineer,Mechanical Design Engineer,ZipRecruiter,Mechanical Design Engineers create and develop...,"{'Employee Assistance Programs (EAP), Tuition ...","Mechanical engineering CAD software (e.g., Sol...","Design mechanical systems, components, and pro...",The Hershey Company,"{""Sector"":""Food and Beverage/Confectionery"",""I..."
1615936,618604818190827,2 to 14 Years,M.Tech,$62K-$130K,Warsaw,Poland,51.9194,19.1451,Intern,63621,...,676.387.1572x71877,IT Manager,IT Director,USAJOBS,An IT Director oversees an organizations IT de...,"{'Health Insurance, Retirement Plans, Paid Tim...",Strategic IT planning Leadership and managemen...,Provide strategic leadership for IT department...,EQT,"{""Sector"":""Energy"",""Industry"":""Energy"",""City"":..."
1615937,615471367712200,4 to 15 Years,BCA,$60K-$96K,Ashgabat,Turkmenistan,38.9697,59.5563,Part-Time,114287,...,537.384.6193x5284,Mechanical Engineer,Mechanical Design Engineer,Indeed,Mechanical Design Engineers create and develop...,"{'Tuition Reimbursement, Stock Options or Equi...","Mechanical engineering CAD software (e.g., Sol...","Design mechanical systems, components, and pro...",KLA,"{""Sector"":""Technology"",""Industry"":""Semiconduct..."
1615938,804137342023945,5 to 15 Years,BCA,$65K-$103K,Ouagadougou,Burkina Faso,12.2383,-1.5616,Full-Time,45009,...,(484)257-4755x5346,HR Coordinator,Training Coordinator,Stack Overflow Jobs,Training Coordinators design and implement emp...,"{'Casual Dress Code, Social and Recreational A...",Training program coordination Training materia...,"Coordinate employee training programs, track t...",Mahindra & Mahindra,"{""Sector"":""Automotive"",""Industry"":""Automotive""..."
1615939,404645755314484,1 to 11 Years,BBA,$56K-$109K,Asmara,Eritrea,15.1794,39.7823,Part-Time,87637,...,(989)703-9723,Event Planner,Wedding Planner,USAJOBS,Wedding Planners specialize in organizing wedd...,"{'Transportation Benefits, Professional Develo...",Wedding planning Venue selection Catering and ...,"Specialize in wedding planning, assisting coup...",Ashtead Group,"{""Sector"":""Equipment Rental"",""Industry"":""Equip..."

In [5]:
# .columns is used to show all columns present in dataset
df.columns

Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile'],
      dtype='object')

In [6]:
# .describe() the numerical calculations of numeric columns present in dataset
df.describe()

             Job Id      latitude     longitude  Company Size
count  1.615940e+06  1.615940e+06  1.615940e+06  1.615940e+06
mean   1.548935e+15  1.937743e+01  1.639926e+01  7.370467e+04
std    8.946722e+14  2.355690e+01  7.066762e+01  3.529886e+04
min    1.817948e+11 -4.090060e+01 -1.751982e+02  1.264600e+04
25%    7.740508e+14  5.152100e+00 -1.531010e+01  4.311400e+04
50%    1.547858e+15  1.807080e+01  1.914510e+01  7.363300e+04
75%    2.323729e+15  3.907420e+01  4.757690e+01  1.043000e+05
max    3.099618e+15  7.170690e+01  1.780650e+02  1.348340e+05

In [7]:
# .info() Provides a basic information of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1615940 non-null  int64
 1   Experience        1615940 non-null  object
 2   Qualifications    1615940 non-null  object
 3   Salary Range      1615940 non-null  object
 4   location          1615940 non-null  object
 5   Country           1615940 non-null  object
 6   latitude          1615940 non-null  float64
 7   longitude         1615940 non-null  float64
 8   Work Type         1615940 non-null  object
 9   Company Size      1615940 non-null  int64
 10  Job Posting Date  1615940 non-null  object
 11  Preference        1615940 non-null  object
 12  Contact Person    1615940 non-null  object
 13  Contact           1615940 non-null  object
 14  Job Title         1615940 non-null  object
 15  Role              1615940 non-null  object
 16  Job Portal        1615940 non-null  object
 17  Job Description   1615940 non-null  object
 18  Benefits          1615940 non-null  object
 19  skills            1615940 non-null  object
 20  Responsibilities  1615940 non-null  object
 21  Company           1615940 non-null  object
 22  Company Profile   1610462 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 283.6+ MB

In [8]:
# .shape provide a shape of datset in the form of (rows,columns)
df.shape

(1615940, 23)

In [9]:
# .columnname is used to show any specific column
df.Experience

0          5 to 15 Years
1          2 to 12 Years
2          0 to 12 Years
3          4 to 11 Years
4          1 to 12 Years
               ...
1615935    0 to 12 Years
1615936    2 to 14 Years
1615937    4 to 15 Years
1615938    5 to 15 Years
1615939    1 to 11 Years
Name: Experience, Length: 1615940, dtype: object

In [10]:
# df.Company Profile
# space between columns name are not allowed in data cleaning so we needs to remove this space

In [11]:
# .rename(columns{'old column':'new column'},inplace=True) is used to change the name of any column in Dataset
df.rename(columns={'Job Id': 'Job_Id','Salary Range': 'Salary_Range','Work Type':'Work_Type', 'Company Size':'Company_Size',
       'Job Posting Date':'Job_Posting_Date', 'Contact Person':'Contact_Person','Job Title':'Job_Title', 'Job Portal':'Job_Portal', 'Job Description':'Job_Description', 'Company Profile':'Company_Profile'},inplace=True)

In [12]:
df.columns

Index(['Job_Id', 'Experience', 'Qualifications', 'Salary_Range', 'location',
       'Country', 'latitude', 'longitude', 'Work_Type', 'Company_Size',
       'Job_Posting_Date', 'Preference', 'Contact_Person', 'Contact',
       'Job_Title', 'Role', 'Job_Portal', 'Job_Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company_Profile'],
      dtype='object')

In [13]:
# we can use .head() with single column also
df.Company_Profile.head(5)

0    {"Sector":"Diversified","Industry":"Diversifie...
1    {"Sector":"Financial Services","Industry":"Com...
2    {"Sector":"Insurance","Industry":"Insurance: P...
3    {"Sector":"Energy","Industry":"Mining, Crude-O...
4    {"Sector":"Energy","Industry":"Energy - Oil & ...
Name: Company_Profile, dtype: object

In [14]:
df.head(5)

,Job_Id,Experience,Qualifications,Salary_Range,location,Country,latitude,longitude,Work_Type,Company_Size,...,Contact,Job_Title,Role,Job_Portal,Job_Description,Benefits,skills,Responsibilities,Company,Company_Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

In [15]:
# .isnull() function is used to find null values in dataset
# .sum() calculate the total number of null valuse in single columns
df.isnull().sum()

Job_Id                 0
Experience             0
Qualifications         0
Salary_Range           0
location               0
Country                0
latitude               0
longitude              0
Work_Type              0
Company_Size           0
Job_Posting_Date       0
Preference             0
Contact_Person         0
Contact                0
Job_Title              0
Role                   0
Job_Portal             0
Job_Description        0
Benefits               0
skills                 0
Responsibilities       0
Company                0
Company_Profile     5478
dtype: int64

In [16]:
df.shape

(1615940, 23)

In [17]:
# DataSet is too large so we can remove null values
# .dropna() is used to drop null valuse
df.dropna(inplace=True)

In [18]:
df.isnull().sum()

Job_Id              0
Experience          0
Qualifications      0
Salary_Range        0
location            0
Country             0
latitude            0
longitude           0
Work_Type           0
Company_Size        0
Job_Posting_Date    0
Preference          0
Contact_Person      0
Contact             0
Job_Title           0
Role                0
Job_Portal          0
Job_Description     0
Benefits            0
skills              0
Responsibilities    0
Company             0
Company_Profile     0
dtype: int64

In [19]:
# .drop_duplicates() is used to remove duplicate values in Dataset
df.drop_duplicates(inplace=True)